// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsCfSZEyATdS1zwHZN4L5d0yrmLXQacds',
    appId: '1:627974758158:android:15f7bdd72c9a41f469815f',
    messagingSenderId: '627974758158',
    projectId: 'messaging-app-bf299',
    storageBucket: 'messaging-app-bf299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Cv1aXYK1WpHtxWJTdsi_jHNq19LMjQ0',
    appId: '1:627974758158:ios:832f54ddbb18b50569815f',
    messagingSenderId: '627974758158',
    projectId: 'messaging-app-bf299',
    storageBucket: 'messaging-app-bf299.appspot.com',
    androidClientId:
        '627974758158-6qla55sftblp5e51c6v44m4tttiq9jlr.apps.googleusercontent.com',
    iosClientId:
        '627974758158-t6i98kllm0bv2a8v4o7coi7mm7v8n9v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Cv1aXYK1WpHtxWJTdsi_jHNq19LMjQ0',
    appId: '1:627974758158:ios:26a7a412799b21e969815f',
    messagingSenderId: '627974758158',
    projectId: 'messaging-app-bf299',
    storageBucket: 'messaging-app-bf299.appspot.com',
    androidClientId:
        '627974758158-6qla55sftblp5e51c6v44m4tttiq9jlr.apps.googleusercontent.com',
    iosClientId:
        '627974758158-dl0t92eapvt96sag8slup9p31oekj1v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
